### PR TITLE
Fix multi-mode NAMES reply and track user channel mode changes

### LINKED ISSUE #67: kiwiirc web client problem with owner and admin in nicklist
Some problem rendering owner and admin in nicklist : 
https://imgur.com/a/0pdS83D

### PR DESCRIPTION
**Pull request by ItsOnlyBinary**
closes #67

### CODE REVIEW

File: src/worker/upstreamcommands.js [hunk 1]
```diff
@@ -554,12 +554,25 @@ commands.MODE = async function(msg, con) {
...
-            // Only tracking channel modes so skip none channel modes like +o
+        if (m.type === chanModeTypes.A || m.type === chanModeTypes.Unknown) {
             // Skip list based type A channel modes like +b
+            // Skip unknown type modes
+            return;
+        }
+
+        if (m.type === chanModeTypes.User) {
+            // Update user prefixes
+            let user = buffer.users[m.param];
```
Comment (prawnsalad) [inline src/worker/upstreamcommands.js:565]: `m.param` needs to be normalised to `(m.param || '').toLowerCase()`
